## Determines only the particles that do not decay to anything. The result
## is a list of TParticle objects that have not decayed. It is possible to
## restrict the list to final decay states of a specific particle.
## 
## The required input parameters:
##  particles - A TClonesArray of TParticle objects generated by TPythia
##  particle - The index of the top-level particle for whose decay products
##             to look at
##  ignoreGamma - A boolean indicating whether to ignore any particles resulting
##                from radiating a photon. (Default: False)
def final_state_particles(particles,particle,ignoreGamma=False):
    particle=particles.At(particle)
    if particle.GetNDaughters()==0:
        if particle.GetPdgCode()==22 and ignoreGamma:
            return []
        else:
            return [particle]

    products=list()
    for i in range(particle.GetFirstDaughter(),particle.GetFirstDaughter()+particle.GetNDaughters()):
        product=particles.At(i)
        if product.GetPdgCode()==22 and ignoreGamma:
            continue # Ignore random gamma radiation
        products.extend(final_state_particles(particles,i,ignoreGamma))
    return products

## Find the last occurance of a particle inside the list of particles.
##
## The required input parameters:
##  particles - A TClonesArray of TParticle objects generated by TPythia
##  pdgCode - The pdg code of the particle to look for
def find_last_particle(particles,pdgCode):
    for i in range(particles.GetEntries()-1,-1,-1):
        particle=particles.At(i)
        if(particle.GetPdgCode()==pdgCode):
            return particle
    return None

## Prints out the information of a particle
## 
## The required inputs parameters are:
##  particle - A TParticle object whose information to print out
def print_info(particle):
    print "%10s\t%d\t%d\t%0.2f\t%0.2f\t%0.2f\t%0.2f"%(particle.GetName(),
                                                    particle.GetFirstDaughter(),
                                                    particle.GetLastDaughter(),
                                                    particle.Px(),
                                                    particle.Py(),
                                                    particle.Pz(),
                                                    particle.Energy())
