## Determines only the particles that do not decay to anything. The result
## is a list of TParticle objects that have not decayed. It is possible to
## restrict the list to final decay states of a specific particle.
## 
## The required input parameters:
##  particles - A TClonesArray of TParticle objects generated by TPythia
##  idx - The index of the top-level particle for whose decay products to look at
##  ignoreRadiation - Whether to ignore products that have radiated off the particle.
##                    Radiations are defined as decays where any daughter has the
##                    same PDG ID as the parent. (Defaut: True)
def final_state_particles(particles,idx,ignoreRadiation=True):
    particle=particles.At(idx)

    if(particle.GetNDaughters()==0):
        return [particle]

    products_all=list()
    products_my=list()
    for i in range(particle.GetFirstDaughter(),particle.GetFirstDaughter()+particle.GetNDaughters()):
        products_current=final_state_particles(particles,i,ignoreRadiation)

        products_all.extend(products_current)
            
        daugther=particles.At(i)
        if daugther.GetPdgCode()==particle.GetPdgCode():
            products_my.extend(products_current)

    if len(products_my)!=0 and ignoreRadiation:
        return products_my
    else:
        return products_all


## Find the last occurance of a particle inside the list of particles.
##
## The required input parameters:
##  particles - A TClonesArray of TParticle objects generated by TPythia
##  pdgCode - The pdg code of the particle to look for
def find_last_particle(particles,pdgCode):
    for i in range(particles.GetEntries()-1,-1,-1):
        particle=particles.At(i)
        if(particle.GetPdgCode()==pdgCode):
            return particle
    return None

## Prints out the information of a particle
## 
## The required inputs parameters are:
##  particle - A TParticle object whose information to print out
def print_info(particle):
    print "%10s\t%d\t%d\t%0.2f\t%0.2f\t%0.2f\t%0.2f"%(particle.GetName(),
                                                    particle.GetFirstDaughter(),
                                                    particle.GetLastDaughter(),
                                                    particle.Px(),
                                                    particle.Py(),
                                                    particle.Pz(),
                                                    particle.Energy())
